### ISSUE TITLE
Release SDK

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-sdk#141]
Time to cut a new release of the sdk so we can use the two new /seen and /users endpoints and updated /submissions and /replies endpoints in the SecureDrop Client.

- [x] Merge changelog
- [x] Push 0.2.0 tag
- [x] Push source tarball to pypi https://pypi.org/project/securedrop-sdk/
- [x] Build wheel and upload to fpf pypi mirror

**Comment by emkll** [comment]
Closed via https://github.com/freedomofpress/securedrop-debian-packaging/pull/204
