### ISSUE TITLE
Adapt SecureDrop SDK to SecureDrop Proxy Behavior

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-sdk#16]
The SecureDrop Qubes OS proxy modifies requests with non-JSON responses (see https://github.com/freedomofpress/securedrop-proxy) - it uses `qvm-move` for those submissions. The SecureDrop SDK has to account for this behavior.

**Comment by kushaldas** [comment]
I think this part should be done by the proxy itself. For example, when the proxy gets a call to download a file, it will use the SDK API to download the file and then will use `qvm-*` command to move it to the right vm. 
I will add an example below after getting back online.
