### ISSUE TITLE
make global var `proxyvname` injectable

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop-sdk#29]
This should probably be part of the `API` class since it doesn't need to be directly accessed by devs.

**Comment by heartsucker** [comment]
Actually this is a bit more complicated than I originally realized. We shouldn't be reading `/etc/` for a config for the API. This should all be loaded via `API.__init__()`. I know we in general are trying to make this lib specifically for use in the Qube workstation, but having a fixed global place to configs for the API library as well as a local place for configs for the Qt GUI clients feels wrong.

**Comment by kushaldas** [comment]
I did that initial config as I use different vms for testing/development. We can just remove this as a whole in the next release. This was purely to help me with development.

**Comment by heartsucker** [comment]
Ok cool. Question answered.

**Comment by redshiftzero** [comment]
relevant to #43 😉

**Comment by redshiftzero** [comment]
this is now the case: https://github.com/freedomofpress/securedrop-sdk/blob/master/sdclientapi/__init__.py#L21
