### ISSUE TITLE
add `black` code format check to ci

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop-sdk#50]
Currently CI is run in docker so we can't easily run the code formatter (it requires python 3.6+) and then do a `[ "$(git status --porcelain | wc -l)" -eq 0 ]` during CI to check that the committer properly formatted their code.

**Comment by eloquence** [comment]
Closing in favor of #123 for a clearer specification; note that we can now use `black --check` in CI, not sure if that arg existed when the issue was filed.
