### ISSUE TITLE
Add developer documentation

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-sdk#6]
As part of the first release of the SDK, we should document it for developers, including:
- installation
- usage
- contribution guide

Scaffolding exists in https://github.com/freedomofpress/sdclientapi/tree/master/docs which needs to be built out.

**Comment by redshiftzero** [comment]
Since development over in client land is proceeding, this is worth adding to the next sprint. Note that we should add these docs to the main SecureDrop repository since:

1. we want more visibility re: the SDK for developers, and
2. the expectation is that we will be releasing this SDK as officially supported in 0.10.0, the next regular release

**Comment by redshiftzero** [comment]
We're not officially releasing this SDK in 0.10.0 as we need to at minimum have documentation in the SecureDrop docs regarding how to use this project, and how to contribute to it. 

In addition we should include the following SDK-related notes in the documentation: 

1. Add a note for maintainers in the docs to ensure that mock requests/responses are regenerated as part of testing PRs which modify the SDK logic. 

2. Add to the QA procedures a step to regenerate all test files at minimum before release (this is a guard against a change being made on the server side). 

We can consider/discuss adding integration tests in CI (though this only covers the HTTP case and not the securedrop-proxy case without some additional work), but until then we need to do the above steps to prevent bugs from being merged or drift between the SDK and the server logic.

**Comment by heartsucker** [comment]
I think it would be useful to remove `pipenv` (https://github.com/freedomofpress/securedrop-sdk/issues/66) before doing this ticket since it would drastically change the docs.

**Comment by redshiftzero** [comment]
this was done
