### ISSUE TITLE
Remove pipenv

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop-sdk#66]
We aggressively pin dependencies using pipenv, but these pins aren't propagated to consumers of this lib. We should allow this lib to depend on a broader range of versions for each dependency so that devs building it locally will pull in different versions and make it more likely that we flush out bugs.

**Comment by kushaldas** [comment]
>We aggressively pin dependencies using pipenv, but these pins aren't propagated to consumers of this lib.

Means?

**Comment by heartsucker** [comment]
After chatting in gitter, I think the solution would be to simply remove use of `Pipfile.lock` in CI and print the results of `pipenv run pip freeze` just to get some insight into the state of the environment. Does anyone object to that?
