### ISSUE TITLE
SDK should handle timeouts

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop-sdk#79]
Right now in the client we use Qt machinery to handle timeouts for API calls. This ends up being rather complex. It would be more convenient to handle timeouts in the SDK so that methods that call the API simple raise `ApiTimeoutError`s instead.

**Comment by creviera** [comment]
Agreed. It'll make queue development simpler and overall improve maintainability.

Right now we have separate threads for timeouts and api calls. Api calls can either result in success (which returns True or None -- I believe that is still being disputed) or an error (returns an Exception). It would make sense for a timeout for an api call to be just another type of error. 

Also it makes sense for the SDK to decide how long a call to the server should take and how we want to retry.

**Comment by heartsucker** [comment]
If we want to add retries to the SDK, that should be a separate issue. It's related, but I think for scoping reasons we should't treat them as the same.
